bases:
  - ../../base  
namespace: dev 
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: myweb
  path: deployment_var.yaml
- target:
    group: ""
    version: v1
    kind: Service
    name: myweb
  path: service_var.yaml
